#!/usr/bin/env python3
from __future__ import annotations

import json
import math
import random
import wave
from array import array
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTENT = ROOT / "shared-content"
AUDIO_MANIFEST = CONTENT / "audio" / "manifests" / "audio_manifest.json"


def write_wav(path: Path, samples: list[float], sample_rate: int = 44100) -> float:
    path.parent.mkdir(parents=True, exist_ok=True)
    pcm = array("h", [max(-32768, min(32767, int(sample * 32767))) for sample in samples])
    with wave.open(str(path), "wb") as handle:
        handle.setnchannels(1)
        handle.setsampwidth(2)
        handle.setframerate(sample_rate)
        handle.writeframes(pcm.tobytes())
    return len(samples) / sample_rate


def envelope(t: float, duration: float, attack: float = 0.01, release: float = 0.12) -> float:
    if t < attack:
        return t / attack
    if t > duration - release:
        return max(0.0, (duration - t) / release)
    return 1.0


def page_flip(path: Path) -> float:
    sr = 44100
    duration = 0.42
    rng = random.Random(1207)
    samples: list[float] = []
    last = 0.0
    for n in range(int(sr * duration)):
        t = n / sr
        sweep = math.sin(2 * math.pi * (340 + 920 * t) * t) * 0.08
        noise = (rng.random() * 2 - 1) * (0.18 if 0.06 < t < 0.31 else 0.06)
        last = last * 0.72 + noise * 0.28
        samples.append((last + sweep) * envelope(t, duration, 0.015, 0.18))
    return write_wav(path, samples, sr)


def button_tap(path: Path) -> float:
    sr = 44100
    duration = 0.14
    samples = []
    for n in range(int(sr * duration)):
        t = n / sr
        tone = math.sin(2 * math.pi * 620 * t) * 0.10 + math.sin(2 * math.pi * 980 * t) * 0.045
        samples.append(tone * envelope(t, duration, 0.004, 0.10))
    return write_wav(path, samples, sr)


def ambient(path: Path, seed: int, base_freq: float) -> float:
    sr = 44100
    duration = 14.0
    rng = random.Random(seed)
    samples = []
    drift = 0.0
    for n in range(int(sr * duration)):
        t = n / sr
        drift = drift * 0.999 + (rng.random() * 2 - 1) * 0.001
        pad = math.sin(2 * math.pi * base_freq * t) * 0.018
        fifth = math.sin(2 * math.pi * base_freq * 1.5 * t + 0.7) * 0.010
        shimmer = math.sin(2 * math.pi * (base_freq * 3.0 + drift * 20) * t) * 0.004
        air = (rng.random() * 2 - 1) * 0.006
        samples.append((pad + fifth + shimmer + air) * 0.58)
    return write_wav(path, samples, sr)


def sparkle(path: Path, seed: int) -> float:
    sr = 44100
    duration = 2.8
    rng = random.Random(seed)
    samples = [0.0 for _ in range(int(sr * duration))]
    for burst in range(9):
        start = int(sr * (0.18 + burst * 0.25 + rng.random() * 0.08))
        freq = 980 + rng.random() * 900
        length = int(sr * (0.12 + rng.random() * 0.08))
        for n in range(length):
            idx = start + n
            if idx >= len(samples):
                break
            t = n / sr
            env = math.exp(-t * 18.0)
            samples[idx] += math.sin(2 * math.pi * freq * t) * 0.07 * env
            samples[idx] += math.sin(2 * math.pi * freq * 1.5 * t) * 0.025 * env
    return write_wav(path, samples, sr)


def water_ripple(path: Path, seed: int) -> float:
    sr = 44100
    duration = 3.2
    rng = random.Random(seed)
    samples = []
    wobble = 0.0
    for n in range(int(sr * duration)):
        t = n / sr
        wobble = wobble * 0.996 + (rng.random() * 2 - 1) * 0.004
        tone = math.sin(2 * math.pi * (210 + wobble * 35) * t) * 0.018
        shimmer = math.sin(2 * math.pi * (510 + wobble * 80) * t) * 0.010
        noise = (rng.random() * 2 - 1) * 0.010
        samples.append((tone + shimmer + noise) * envelope(t, duration, 0.08, 0.65))
    return write_wav(path, samples, sr)


def candidate(output_file: str, duration: float, asset_type: str) -> dict:
    now = datetime.now(timezone.utc).replace(microsecond=0).isoformat()
    return {
        "outputFile": output_file,
        "status": "synthetic_draft",
        "provider": "local_python_synth",
        "tool": "local_python_synth",
        "model": "procedural_audio_draft",
        "generationStatus": "generated",
        "timestamp": now,
        "duration": round(duration, 3),
        "normalization": {"applied": True, "targetPeakDb": -6.0, "method": "procedural gain staging"},
        "sourceFile": None,
        "text": asset_type,
        "reviewer": None,
        "reviewDate": None,
        "rejectionReason": None,
        "notes": "Generated procedural audio draft. Not final sound design.",
        "sourceLicense": "First-party procedural draft generated by tools/generate_sound_drafts.py; no third-party samples.",
        "culturalReviewStatus": "not_reviewed",
        "childSafetyReviewStatus": "not_reviewed",
        "productionApprovalStatus": "not_approved",
    }


def upsert(entry: dict, output_file: str, duration: float) -> None:
    entry.setdefault("candidates", [])
    entry["candidates"] = [item for item in entry["candidates"] if item.get("outputFile") != output_file]
    entry["candidates"].append(candidate(output_file, duration, entry.get("assetType", "audio")))
    entry["outputFile"] = output_file
    entry["tool"] = "local_python_synth"
    entry["model"] = "procedural_audio_draft"
    entry["duration"] = round(duration, 3)
    entry["status"] = "synthetic_draft"
    entry["generationStatus"] = "generated"


def main() -> int:
    manifest = json.loads(AUDIO_MANIFEST.read_text(encoding="utf-8"))

    page_flip_path = "audio/synthetic-draft/ui/page-flip.wav"
    button_tap_path = "audio/synthetic-draft/ui/button-tap.wav"
    durations = {
        page_flip_path: page_flip(CONTENT / page_flip_path),
        button_tap_path: button_tap(CONTENT / button_tap_path),
    }

    for entry in manifest.get("uiSoundEntries", []):
        if entry.get("assetType") == "page_flip_sound":
            upsert(entry, page_flip_path, durations[page_flip_path])
        if entry.get("assetType") == "button_tap_sound":
            upsert(entry, button_tap_path, durations[button_tap_path])

    bases = {
        "sun-and-moon": 174.0,
        "gold-axe-silver-axe": 196.0,
        "tiger-and-persimmon": 164.0,
        "heungbu-and-nolbu": 185.0,
        "red-bean-porridge-grandma": 146.0,
    }
    for index, entry in enumerate(manifest.get("ambientEntries", []), start=1):
        old = entry.get("outputFile", "")
        slug = old.split("/books/")[-1].split("/ambient/")[0]
        output = f"audio/synthetic-draft/books/{slug}/ambient/ambient-loop.wav"
        duration = ambient(CONTENT / output, seed=2200 + index, base_freq=bases.get(slug, 174.0))
        upsert(entry, output, duration)

    sfx_entries: list[dict] = []
    for asset_type, output, seed, base_freq in [
        ("nighttime_ambience", "audio/synthetic-draft/sfx/nighttime-ambience.wav", 3301, 132.0),
        ("forest_ambience", "audio/synthetic-draft/sfx/forest-ambience.wav", 3302, 168.0),
        ("bedtime_ambience", "audio/synthetic-draft/sfx/bedtime-ambience.wav", 3303, 110.0),
    ]:
        duration = ambient(CONTENT / output, seed=seed, base_freq=base_freq)
        sfx_entries.append(
            {
                "assetType": asset_type,
                "outputFile": output,
                "tool": "local_python_synth",
                "model": "procedural_audio_draft",
                "duration": round(duration, 3),
                "status": "synthetic_draft",
                "generationStatus": "generated",
                "sourceLicense": "First-party procedural draft generated by tools/generate_sound_drafts.py; no third-party samples.",
                "candidates": [candidate(output, duration, asset_type)],
            }
        )

    for asset_type, output, generator, seed in [
        ("lantern_firefly_sparkle", "audio/synthetic-draft/sfx/lantern-firefly-sparkle.wav", sparkle, 3401),
        ("water_ripple", "audio/synthetic-draft/sfx/water-ripple.wav", water_ripple, 3402),
    ]:
        duration = generator(CONTENT / output, seed=seed)
        sfx_entries.append(
            {
                "assetType": asset_type,
                "outputFile": output,
                "tool": "local_python_synth",
                "model": "procedural_audio_draft",
                "duration": round(duration, 3),
                "status": "synthetic_draft",
                "generationStatus": "generated",
                "sourceLicense": "First-party procedural draft generated by tools/generate_sound_drafts.py; no third-party samples.",
                "candidates": [candidate(output, duration, asset_type)],
            }
        )

    manifest["sfxEntries"] = sfx_entries

    AUDIO_MANIFEST.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print("Generated synthetic_draft page-turn, button, ambient, and story SFX audio.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
